export default interface TextareaProps {
  name?: string,
  id?: string,
  label?: any,
  value?: string,
  rows?: number,
  prefix?: string,
  suffix?: string,
  autocomplete?: string,
  spellcheck?: boolean,
  classes?: string,
  errorMessage?: any,
  children?: any,
  describedBy?: string,
  attributes?: any,
}
