export default interface DateInputProps {
  id?: string,
  dayLabel?: string,
  monthLabel?: string,
  yearLabel?: string,
  autocompleteDay?: string,
  autocompleteMonth?: string,
  autocompleteYear?: string,
  name?: string,
  classes?: string,
  value?: any,
  errorMessage?: string,
  errorDay?: boolean,
  errorMonth?: boolean,
  errorYear?: boolean, 
  children?: any,
  attributes?: any,
}
