export default interface CharacterCountProps {
  name?: string,
  id?: string,
  autocomplete?: string,
  children?: any,
  maxLength?: number,
  textareaDescriptionText?: string,
  value?: string,
  errorMessage?: any,
  rows?: number,
  maxWords?: number,
  threshold?: number,
  charactersUnderLimitText?: any,
  charactersAtLimitText?: string,
  charactersOverLimitText?: any,
  wordsUnderLimitText?: any,
  wordsAtLimitText?: string,
  wordsOverLimitText?: any,
  classes?: string,
  attributes?: any,
  formGroup?: any,
  countMessage?: any,
  spellcheck?: boolean,
  describedBy?: string,
}